FROM ultralytics/ultralytics:latest
COPY setup.py setup.py
COPY requirements.txt requirements.txt
RUN pip install --upgrade pip
RUN pip install -e .
COPY facetally facetally/
CMD python facetally/interface/main.py
